linters:
  enable-all: true

issues:
  exclude-rules:
  - path: _test\.go
    linters:
    - lll

linters-settings:
  depguard:
    rules:
      main:
        files:
        - $all
        - "!$test"
        allow:
        - $gostd
        - github.com/gin-gonic/gin
        - github.com/kelseyhightower/envconfig
      test:
        files:
        - $test
        allow:
        - $gostd
        - github.com/stretchr/testify/require
  gci:
    sections:
    - standard
    - default
    - prefix(github.com/kuoss/myip)
  gocritic:
    enabled-tags:
    - diagnostic
    - style
    - performance
    - experimental
    - opinionated
