name: pull-request
on:
  pull_request:
    types: [opened, reopened, synchronize]
permissions:
  contents: read
  pull-requests: write

jobs:
  go-fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: Jerome1337/gofmt-action@v1.0.5
      with:
        gofmt-path: '.'
        gofmt-flags: '-l -d'

  misspell:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: make misspell

  gocyclo:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
    - run: make gocyclo

  goimports:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: Jerome1337/goimports-action@v1.0.3

  go-vet:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v4
      with:
        go-version: '^1.21.5'
    - uses: actions/checkout@v3
    - run: go vet ./...

  staticcheck:
    strategy:
      fail-fast: false
      matrix:
        os:  ["ubuntu-latest"]
        go:  ["1.21.x"]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - uses: WillAbides/setup-go-faster@v1.8.0
      with:
        go-version: ${{ matrix.go }}
    - uses: dominikh/staticcheck-action@v1.3.0
      with:
        version: "2022.1.3"
        install-go: false
        cache-key: ${{ matrix.go }}

  golangci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        cache: false
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        args: --timeout 5m

  go-test-failfast:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v4
      with:
        go-version: '^1.21.5'
    - uses: actions/checkout@v3
    - run: go test ./... -race -failfast

  go-test-coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v4
      with:
        go-version: '^1.21.5'
    - uses: actions/checkout@v3
    - run: go test ./... -race -covermode=atomic -coverprofile=coverage.out
    - uses: codecov/codecov-action@v3
    - run: go install github.com/mattn/goveralls@latest
    - run: goveralls -coverprofile=coverage.out -service=github
      env:
        COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  go-licenses:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v4
      with:
        go-version: '^1.21.5'
    - uses: actions/checkout@v3
    - run: go install github.com/google/go-licenses@v1.6.0    
    - run: go-licenses check .

  docker-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
    - uses: actions/checkout@v3
    - uses: docker/build-push-action@v4
      with:
        context: .
        push: false
        build-args: |
          VERSION=development
