name: release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read
  packages: write
  id-token: write # needed for signing the images with GitHub OIDC Token

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: docker/metadata-action@v5
      id: docker_metadata
      with:
        images: ghcr.io/${{ github.repository }}
        tags: |
          type=semver,pattern=v{{version}}
          type=semver,pattern=v{{major}}.{{minor}}
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}        
    - uses: docker/build-push-action@v5
      id: build_and_push
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.docker_metadata.outputs.tags }}
        labels: ${{ steps.docker_metadata.outputs.labels }}
    - uses: sigstore/cosign-installer@v3
      if: github.event_name != 'pull_request'
    - name: Sign the images with GitHub OIDC Token
      if: github.event_name != 'pull_request'
      env:
        DIGEST: ${{ steps.build_and_push.outputs.digest }}
        TAGS: ${{ steps.docker_metadata.outputs.tags }}
      run: |
        images=""
        for tag in ${TAGS}; do
          images+="${tag}@${DIGEST} "
        done
        cosign sign --yes ${images}
